default_platform(:ios)
platform :ios do
  desc "Build and upload to TestFlight via API key"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "./AuthKey.p8",
      in_house: false
    )
    gym(project: "Tyrfrost3D/Tyrfrost3D.xcodeproj",
        scheme: "Tyrfrost3D",
        configuration: "Release",
        export_method: "app-store",
        include_symbols: false,
        include_bitcode: false,
        silent: true)
    pilot(skip_waiting_for_build_processing: true)
  end
end
